### ISSUE TITLE
Landing-Page

### ISSUE THREAD

**Issue by ghost** [HRISHIKESHPAWAR/Portfolio-Web-Page#4]
- [x] Complete Landing-Page
- [x] use semantics tags

**Comment by hrishipawar24** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Startup India</title>
    <style>
           *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
   }
   body{
    font-family: Verdana, Geneva, Tahoma, sans-serif;
   }
   UL{
    list-style: none;
    text-align: end;
    padding: 30px;
    background-color: black;
    color: aliceblue;
   }
   li{
    display: inline;
    padding: 20px;
   }
   li:hover{
    color: blue;
   }
        body {
    font-size: 24px;
    font-style: oblique;
    text-align: center;
    color: #1d3557;
    background-color: #a8dadc;
    
}
article {
    margin: 25px;
    padding: 44px;
    border-radius: 20px;
    background-color: azure;
}
    </style>
</head>
<body>
    <nav>
        <ul>
           <li>Home</li>
           <li>Product</li>
           <li>Services</li>
        </ul>
       </nav>
    <h1>Startup India</h1>
       <p>Startup India is an initiative of the Government of India</p>
        
<article>
    <img width="100px" src="https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Startup_India_logo.svg/800px-Startup_India_logo.svg.png" 
    alt="Startup India images" 
    srcset="">
    <p>Startup India is an initiative of the Government of India. The campaign was first announced by Indian Prime Minister, Narendra Modi during his speech on 15 August 2015.

        The action plan of this initiative is focussing on three areas:
        
        Simplification and Handholding.
        Funding Support and Incentives.
        Industry-Academia Partnership and Incubation.
        An additional area relating to this initiative is to discard restrictive States Government policies within this domain, such as License Raj, Land Permissions, Foreign Investment Proposals, and Environmental Clearances. It was organized by The Department for promotion of industry and internal trade (DPI&IT).
        
        A startup defined as an entity that is headquartered in India, which was opened less than 10 years ago, and has an annual turnover less than ₹100 crore (US$13 million). Under this initiative, the government has already launched the I-MADE program, to help Indian entrepreneurs build 10 lakh (1 million) mobile app start-ups, and the MUDRA Bank's scheme (Pradhan Mantri Mudra Yojana), an initiative which aims to provide micro-finance, low-interest rate loans to entrepreneurs from low socioeconomic backgrounds. Initial capital of ₹20,000 crore (equivalent to ₹240 billion or US$3.0 billion in 2020) has been allocated for this scheme.
        
        Recently Indian Prime Minister announced "India will celebrate January 16 as ‘National Start-up Day". Hon’ble PM awarded 48 startups on the eve of first National startup day. This time from Pune, Maharashtra, four startups got the award. </p>
</article>
</body>
</html>
